name: Testes Automatizados Blog Agi

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permite execução manual

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Configurar Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Verificar versão do Chrome
      run: chrome --version
    
    - name: Garantir permissão do gradlew
      run: chmod +x ./gradlew
    
    - name: Executar testes
      run: ./gradlew test -Dbrowser=chrome-headless
    
    - name: Gerar relatório Allure
      if: always()
      run: |
        curl -o allure-2.22.0.zip -OLs https://github.com/allure-framework/allure2/releases/download/2.22.0/allure-2.22.0.zip
        unzip -o allure-2.22.0.zip -d .
        ./allure-2.22.0/bin/allure generate build/allure-results -o build/allure-report --clean
    
    - name: Publicar resultados dos testes
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          build/reports/tests/
          build/allure-report/
          logs/
  
  publish-report:
    needs: test
    runs-on: ubuntu-latest
    if: success() || failure()
    permissions:
      pages: write
      id-token: write
    
    # Configuração do ambiente de GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Download dos relatórios
      uses: actions/download-artifact@v3
      with:
        name: test-reports
        path: reports
        
    - name: Configurar GitHub Pages
      uses: actions/configure-pages@v3
      
    - name: Upload do artefato para Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'reports/build/allure-report'
        
    - name: Publicar no GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2 